[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  VITE_API = "https://bubblepanel-webui-1.onrender.com"

[[redirects]]
  from = "/api/*"
  to   = "https://bubblepanel-webui-1.onrender.com/:splat"
  status = 200
  force  = true
