[build]
  command = "npm ci && npm run --prefix frontend build"
  publish = "frontend/dist"


[build.environment]
  VITE_API = "/api"

[[redirects]]
  from = "/api/*"
  to   = "https://bubblepanel-webui-1.onrender.com/:splat"
  status = 200
  force  = true
